FUZZ_MARKER = "FUZZ"

DEFAULT_PAYLOAD_FILE = "payloads.txt"
DEFAULT_TIMEOUT = 5
DEFAULT_THREADS = 10

SUSPICIOUS_STATUS_CODES = [500, 502, 503, 504]

SLOW_RESPONSE_THRESHOLD = 2.0
LARGE_RESPONSE_THRESHOLD = 5000